"""Add AbitChatInfo.greeting_photo_file_id field

Revision ID: 0ad3332dbeac
Revises: 74e8df3a529a
Create Date: 2023-07-30 20:40:38.843494+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad3332dbeac'
down_revision = '74e8df3a529a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abit_chat_info', sa.Column('greeting_photo_file_id', sa.String(length=100), nullable=False,
                                              server_default='broken_id'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('abit_chat_info', 'greeting_photo_file_id')
    # ### end Alembic commands ###
