"""Add required document models

Revision ID: 0f82d2e248c6
Revises: 377a6160563e
Create Date: 2023-10-30 13:45:04.653421+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f82d2e248c6'
down_revision = '377a6160563e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('applicant_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_chat_id'], ['applicant_chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['applicant_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'applicant_chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('required_documents')
    op.drop_table('applicant_documents')
    # ### end Alembic commands ###
