"""Add AdmissionCommitteInfo and AdmissionCommitteTimetableRecord models

Revision ID: 2234d59848c3
Revises: 15f5768bb6cd
Create Date: 2023-08-05 12:01:35.181745+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2234d59848c3'
down_revision = '15f5768bb6cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_committe_info',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('queue_url', sa.String(length=500), nullable=True),
    sa.Column('required_documents_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['abit_chat_info.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('admission_committe_timetable',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=False),
    sa.Column('work_end', sa.Time(), nullable=False),
    sa.Column('committe_chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['committe_chat_id'], ['admission_committe_info.chat_id'], ),
    sa.PrimaryKeyConstraint('committe_chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admission_committe_timetable')
    op.drop_table('admission_committe_info')
    # ### end Alembic commands ###
