"""Add missing id column on admission_committee_timetable

Revision ID: 2d5fb7625b09
Revises: 63920cdc14d4
Create Date: 2023-11-01 10:31:56.237912+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2d5fb7625b09"
down_revision = "63920cdc14d4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "admission_committee_timetable_pkey", "admission_committee_timetable", "primary"
    )
    op.add_column(
        "admission_committee_timetable",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
    )
    op.create_primary_key(
        "admission_committee_timetable_pkey",
        "admission_committee_timetable",
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "admission_committee_timetable_pkey", "admission_committee_timetable", "primary"
    )
    op.drop_column("admission_committee_timetable", "id")
    op.create_primary_key(
        "admission_committee_timetable_pkey",
        "admission_committee_timetable",
        ["applicant_chat_id"],
    )
    # ### end Alembic commands ###
