"""Add useful link models

Revision ID: 3a6e40f0c8d0
Revises: cf7f461d7f92
Create Date: 2023-10-30 14:09:42.809896+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a6e40f0c8d0"
down_revision = "cf7f461d7f92"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "useful_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "applicant_chat_useful_links",
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("applicant_chat_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["applicant_chat_id"], ["applicant_chats.chat_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["link_id"], ["useful_links.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("link_id", "applicant_chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("applicant_chat_useful_links")
    op.drop_table("useful_links")
    # ### end Alembic commands ###
