"""Add missing id column to chat_member_limitations

Revision ID: 4bf0c28ac3a2
Revises: 207864a00f24
Create Date: 2023-11-01 13:55:42.878803+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bf0c28ac3a2"
down_revision = "207864a00f24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_member_limitations",
        sa.Column("id", sa.Integer(), nullable=False, primary_key=True),
    )
    # ### end Alembic commands ###
    op.drop_constraint(
        "chat_member_limitations_pkey", "chat_member_limitations", "primary"
    )
    op.create_primary_key(
        "chat_member_limitations_pkey", "chat_member_limitations", ["id"]
    )


def downgrade() -> None:
    op.drop_constraint(
        "chat_member_limitations_pkey", "chat_member_limitations", "primary"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_member_limitations", "id")
    # ### end Alembic commands ###
    op.create_primary_key(
        "chat_member_limitations_pkey",
        "chat_member_limitations",
        ["chat_id", "user_id"],
    )
