"""Add missing ApplicantChat model

Revision ID: 631644d659d5
Revises: a86127764355
Create Date: 2023-10-30 12:59:59.340409+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631644d659d5'
down_revision = 'a86127764355'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_chats',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('flood_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('greet_new_members', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flood_chat_id'], ['flood_chats.chat_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant_chats')
    # ### end Alembic commands ###
