"""Fix relationships

Revision ID: 74e8df3a529a
Revises: 11a62d74b651
Create Date: 2023-07-30 18:36:41.868939+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e8df3a529a'
down_revision = '11a62d74b651'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'programs', 'abit_chat_info', ['chat_id'], ['chat_id'])
    op.add_column('useful_links', sa.Column('chat_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'useful_links', 'abit_chat_info', ['chat_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useful_links', type_='foreignkey')
    op.drop_column('useful_links', 'chat_id')
    op.drop_constraint(None, 'programs', type_='foreignkey')
    op.drop_column('programs', 'chat_id')
    # ### end Alembic commands ###
