"""Add ChatMember and SentPinguinRecord models

Revision ID: 7a7f2b705b37
Revises: d6c04595643a
Create Date: 2023-08-02 09:36:18.543502+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a7f2b705b37'
down_revision = 'd6c04595643a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['abit_chat_info.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sent_pinguin_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('chat_member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat_member_id'], ['chat_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_pinguin_records')
    op.drop_table('chat_members')
    # ### end Alembic commands ###
