"""Make the index on ChatMember.user_id and ChatMember.chat_id columns unique

Revision ID: 943147f1b7d5
Revises: 9f4a246713b9
Create Date: 2023-08-02 11:32:48.044624+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943147f1b7d5'
down_revision = '9f4a246713b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_members__user_id__chat_id', table_name='chat_members')
    op.create_index('ix_chat_members__user_id__chat_id', 'chat_members', ['user_id', 'chat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_members__user_id__chat_id', table_name='chat_members')
    op.create_index('ix_chat_members__user_id__chat_id', 'chat_members', ['user_id', 'chat_id'], unique=False)
    # ### end Alembic commands ###
