"""Add index on ChatMember.user_id and ChatMember.chat_id columns

Revision ID: 9f4a246713b9
Revises: 7a7f2b705b37
Create Date: 2023-08-02 10:33:25.102805+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4a246713b9'
down_revision = '7a7f2b705b37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chat_members__user_id__chat_id', 'chat_members', ['user_id', 'chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_members__user_id__chat_id', table_name='chat_members')
    # ### end Alembic commands ###
