"""Rewrite chat models

Revision ID: a86127764355
Revises: bfdbd528dedc
Create Date: 2023-10-30 09:55:55.581317+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a86127764355'
down_revision = 'bfdbd528dedc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('invite_link', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flood_chats',
    sa.Column('chat_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.drop_table('programs')
    op.drop_index('ix_chat_members__user_id__chat_id', table_name='chat_members')
    op.drop_table('sent_penguin_records')
    op.drop_table('chat_members')
    op.drop_table('admission_committe_timetable')
    op.drop_table('admission_committe_info')
    op.drop_table('useful_links')
    op.drop_table('abit_chat_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_committe_timetable',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('work_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('work_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('committe_chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['committe_chat_id'], ['admission_committe_info.chat_id'], name='admission_committe_timetable_committe_chat_id_fkey')
    )
    op.create_table('useful_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['abit_chat_info.chat_id'], name='useful_links_chat_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='useful_links_pkey')
    )
    op.create_table('admission_committe_info',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('queue_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('required_documents_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['abit_chat_info.chat_id'], name='admission_committe_info_chat_id_fkey'),
    sa.PrimaryKeyConstraint('chat_id', name='admission_committe_info_pkey')
    )
    op.create_table('sent_penguin_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('chat_member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_member_id'], ['chat_members.id'], name='sent_penguin_records_chat_member_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sent_penguin_records_pkey')
    )
    op.create_table('chat_members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['abit_chat_info.chat_id'], name='chat_members_chat_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chat_members_pkey')
    )
    op.create_index('ix_chat_members__user_id__chat_id', 'chat_members', ['user_id', 'chat_id'], unique=False)
    op.create_table('abit_chat_info',
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('flood_chat_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('greeting_photo_file_id', sa.VARCHAR(length=100), server_default=sa.text("'broken_id'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name='abit_chat_info_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('programs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('guide_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['abit_chat_info.chat_id'], name='programs_chat_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='programs_pkey')
    )
    op.drop_table('flood_chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
