"""Add program models

Revision ID: cf7f461d7f92
Revises: 0f82d2e248c6
Create Date: 2023-10-30 14:04:06.203459+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7f461d7f92'
down_revision = '0f82d2e248c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('first_year', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('subject_list_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicant_chat_programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('applicant_chat_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_chat_id'], ['applicant_chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'applicant_chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicant_chat_programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
